version: 1
name: dsrl
manager: micromamba

create:
  commands:
    - micromamba create -n dsrl python=3.9 pip -y
    - micromamba run -n dsrl bash -lc "cd ../dsrl/dppo && pip install -e . && pip install -e .[robomimic] && pip install -e .[gym]"
    - micromamba run -n dsrl bash -lc "cd ../dsrl/stable-baselines3 && pip install -e ."
