version: 1
name: qam
manager: micromamba

create:
  commands:
    - micromamba create -n qam python=3.10 pip -y
    - micromamba run -n qam pip install -r third_party/qam/requirements.txt
    - micromamba run -n qam pip install "git+https://github.com/ARISE-Initiative/robomimic@dde3a6e74886e0768cedf18f8f9c813d47d31ebd"
    - micromamba run -n qam pip install "robosuite==1.4.1"
    - micromamba run -n qam pip install h5py
    - micromamba run -n qam pip install 'jax[cuda12]'
